/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        /* ── New warm redesign palette ── */
        cream:         '#F7F4EF',
        parchment:     '#EDE8E0',
        nude:          '#D4C4B5',
        bark:          '#7B4F3A',
        'bark-light':  '#9B6A52',
        'bark-dark':   '#5A3828',
        olive:         '#A89140',
        'olive-light': '#C4AE58',
        'olive-pale':  '#E8DFB8',
        sage:          '#6B7A5F',
        'sage-light':  '#8A9B7E',
        'sage-dark':   '#4A5742',
        ink:           '#2A1F1A',
        stone:         '#7A6E66',
        'stone-light': '#B0A49C',
        /* ── Legacy aliases (keep admin + old components working) ── */
        rust:          '#7B4F3A',
        'rust-dark':   '#5A3828',
        espresso:      '#2A1F1A',
        gold:          '#A89140',
        'gold-warm':   '#C4AE58',
        'sage-deep':   '#4A5742',
        'blush-soft':  '#EDE8E0',
        blush:         '#D4C4B5',
        success:       '#4A6B42',
        error:         '#7D2E2E',
        obsidian:      '#0D0D0D',
        dark1:         '#111111',
        dark2:         '#151515',
        dark3:         '#1a1a1a',
        dark4:         '#202020',
      },
      fontFamily: {
        cormorant: ['Cormorant Garamond', 'serif'],
        josefin:   ['Josefin Sans', 'sans-serif'],
        dm:        ['DM Sans', 'sans-serif'],
      },
      borderRadius: {
        none:      '0px',
        card:      '4px',
        'card-lg': '8px',
        btn:       '4px',
        pill:      '999px',
        full:      '9999px',
      },
      boxShadow: {
        card:         '0 2px 16px rgba(42,31,26,0.07)',
        'card-hover': '0 8px 32px rgba(42,31,26,0.13)',
        float:        '0 4px 24px rgba(42,31,26,0.10)',
        drawer:       '-4px 0 40px rgba(42,31,26,0.12)',
        hover:        '0 12px 40px rgba(42,31,26,0.14)',
        modal:        '0 32px 80px rgba(42,31,26,0.2)',
        soft:         '0 2px 12px rgba(42,31,26,0.06)',
      },
      animation: {
        marquee:       'marqueeScroll 32s linear infinite',
        'fade-up':     'fadeUp 0.7s cubic-bezier(0.76,0,0.24,1) forwards',
        'fade-in':     'fadeIn 0.5s ease forwards',
        'slide-up':    'slideUp 0.6s cubic-bezier(0.76,0,0.24,1) forwards',
        'scale-in':    'scaleIn 0.4s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'warm-reveal': 'warmReveal 0.9s cubic-bezier(0.76,0,0.24,1) forwards',
        float:         'floatY 6s ease-in-out infinite',
        'float-slow':  'floatY 9s ease-in-out infinite',
        'pulse-olive': 'pulseOlive 2s ease-in-out infinite',
      },
      keyframes: {
        marqueeScroll: {
          from: { transform: 'translateX(0)' },
          to:   { transform: 'translateX(-50%)' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(28px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(40px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.88)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        warmReveal: {
          from: { clipPath: 'inset(0 100% 0 0)' },
          to:   { clipPath: 'inset(0 0% 0 0)' },
        },
        floatY: {
          '0%,100%': { transform: 'translateY(0px)' },
          '50%':     { transform: 'translateY(-10px)' },
        },
        pulseOlive: {
          '0%,100%': { opacity: '1' },
          '50%':     { opacity: '0.4' },
        },
      },
    },
  },
  plugins: [],
}
