services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/auryadeco

volumes:
  mongo_data:
