import api from './api'

export const adminService = {
  getSummary: () => api.get('/admin/analytics/summary'),
  getRevenue: (period) => api.get(`/admin/analytics/revenue?period=${period}`),
  getOrdersByStatus: () => api.get('/admin/analytics/orders-by-status'),
  getTopProducts: (limit = 10) => api.get(`/admin/analytics/top-products?limit=${limit}`),
  getCustomersAnalytics: () => api.get('/admin/analytics/customers'),
  getOrders: (params) => api.get('/admin/orders', { params }),
  getOrder: (id) => api.get(`/admin/orders/${id}`),
  updateOrderStatus: (id, payload) => api.patch(`/admin/orders/${id}/status`, payload),
  updateOrderNotes: (id, payload) => api.patch(`/admin/orders/${id}/notes`, payload),
  getProducts: (params) => api.get('/admin/products', { params }),
  createProduct: (fd) => api.post('/admin/products', fd),
  updateProduct: (id, fd) => api.post(`/admin/products/${id}/update`, fd),
  deleteProduct: (id) => api.delete(`/admin/products/${id}`),
  toggleProduct: (id) => api.patch(`/admin/products/${id}/toggle`),
  getCategories: () => api.get('/admin/categories'),
  createCategory: (data) => api.post('/admin/categories', data),
  updateCategory: (id, data) => api.patch(`/admin/categories/${id}`, data),
  deleteCategory: (id) => api.delete(`/admin/categories/${id}`),
  reorderCategories: (list) => api.patch('/admin/categories/reorder', list),
  getUsers: (params) => api.get('/admin/users', { params }),
  getUser: (id) => api.get(`/admin/users/${id}`),
  getSettings: () => api.get('/admin/settings'),
  updateHeroText: (payload) => api.patch('/admin/settings/hero/text', payload),
  updateHeroImage: (fd) => api.post('/admin/settings/hero/image', fd),
  updateMarquee: (payload) => api.patch('/admin/settings/marquee', payload),
  updateContact: (payload) => api.patch('/admin/settings/contact', payload),
  updateSEO: (payload) => api.patch('/admin/settings/seo', payload),
}
